import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
/*layouts  importacion externa*/
import Arriba from "./_layouts/_Arriba/Arriba";
import Abajo from "./_layouts/_Abajo/Abajo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Arriba></Arriba>
        <div>{children}</div>
        <Abajo></Abajo>
      </body>
      <Script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></Script>
      <Script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></Script>
    </html>
  );
}
