CREATE TABLE celularesBitel (Id SERIAL PRIMARY KEY,
Categoria VARCHAR(50) NOT NULL,
Nserie1 VARCHAR(30) NOT NULL,
Nserie2 VARCHAR(30),
Imagen1 TEXT NOT NULL,
Imagen2 TEXT,
Imagen3 TEXT,
Imagen3D TEXT,
Precio DECIMAL(20, 2) NOT NULL,
Marca VARCHAR(150) NOT NULL,
Ram INT NOT NULL,
Almacenamiento INT NOT NULL,
Bateria INT NOT NULL,
Camara INT NOT NULL,
Pantalla DECIMAL(3, 2) NOT NULL,
Unidades INT NOT NULL,
Descripcion VARCHAR(2000));
create table celularesClaro /*/***/ copia pendeiente(conversar)